import { AppointmentItem } from '@/lib/types';

export const RICH_APPOINTMENTS_DATA: AppointmentItem[] = [
  // Friday, May 16, 2025 (Today)
  {
    id: 'appt-101',
    date: '2025-05-16',
    time: '8:30 AM',
    duration: '2.5 hrs',
    customerName: 'Sarah Johnson',
    customerInitials: 'SJ',
    customerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCNIEpDScyL977tdc-rLYh4_ksq466XZ7OpRPQzY-1HWlRGcv3nDVmyz5hiik8a4BztgOlDE8mwAglsQF7nec16VqxecRAG2BROmD6CQ6akSNSwZjZXabjJAu0lTMjgw8Z5m7gcOPZDP7UlqFU_sNGVJCwd5fNw_Mye6SCB9_SIBuisfYgH-Ry8BYMEIB0B4Fh8D_upZhRp5MafgvVz1iXHsTvXy1oA1byvfOqrP_Xg3cYGC-rQ-oye',
    petName: 'Buddy',
    breed: 'Golden Retriever',
    petEmoji: '🐶',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBLpfCCmF3nlMMcPB9IzYVaUGkIdDklvIQ_giCXNqtgNrHqPlXhU0z5091kzCKslhGzASqTKgCMX0Bojlgdo2iMtDBXfNdVLL10PsCHRw__R3AjRLsDJ1zrtRYcY-EZY0s0zBk6N0c_DCqTg6pMkGt3H2X_skZMdik4aVxfk6p4mk4GLNo1zVj4q4JEgKnTwHyQEvDzMCqWAp8YIbZW2Lup3XrErodWNsEK0FRfQ1tD-9HbzBn6GBO3',
    serviceName: 'Full Groom',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBBjfutMiOMFm_xgpnPXSRM0VFEpxvvkAnnsyn73isVSOKMPsIn3bLsRUmpw-gvs9E_wP9_nEqaEfPJFIWnmf2lBlcB87Tlxo6u1P0DGKt8T4TROyIKu7Q4w7vLW3eeCT-SaN76hfgz92owuvTUGd13jZjo7t2e69OS62d9GxHS8ugRCyIFV_MsRmSNWnhvLFjHvJlsh5iyHTmIuUUK4eAM_pj-Z3sJVex8bqS1_JbkHQePONmSCi2B',
    location: 'Main Location',
    status: 'Scheduled',
    price: 85.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 25.0,
    notes: 'Sensitive skin, hypoallergenic shampoo requested.',
  },
  {
    id: 'appt-102',
    date: '2025-05-16',
    time: '10:30 AM',
    duration: '2.5 hrs',
    customerName: 'Mike Ross',
    customerInitials: 'MR',
    petName: 'Luna',
    breed: 'Poodle',
    petEmoji: '🐕',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCCQYfh-aoz2fC7W-KvLS1gL2xq7frfxZ6qcv8r7m8P005ZR8_TI51l7i4GwpnUdL8bep9DU5Q2WkpChOamX9uf76E29Q2Qbm5RRekYeOHAlSRgnCPPsP4BOn8iepg1BdQEFDNEuQxMPPR78jGL73hFVIvsfsnjDxU-reueYgHhue265vrrAsNfYc56hiYBG9aXS5ewGw4L8Uhbl4vxpR9CUr4xyxO9pL43PLRdbGc059kI8t11rYg2',
    serviceName: 'Full Groom + Add-ons',
    staffName: 'Mike R.',
    staffInitials: 'MR',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDL7AT6yATpe3e2_ExUU5mU6D1E4_S49TaYHu6zjIPreqvBWpmVq80LvgqJJIGl_2fpq3tCj5_o61FDSZYNwhsj210-a-IsS0u7E2QQtaOPTcCxRgXXgBX0E9XFvjZeRnoVkboGCwtue3fhXzg1oXgLdwtjqKQ9_ArUVldrMlGFW3XR9wA5iBLV7Vm7yGxOS6yABY0n-rhEL0Lc7N8BJrhWp_Uc9x5cjAUF95OZLjbbRPw6BNNtD7CR',
    location: 'Main Location',
    status: 'Scheduled',
    price: 120.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 35.0,
    notes: 'Puppy cut, trim teddy face shape, blueberry facial.',
  },
  {
    id: 'appt-103',
    date: '2025-05-16',
    time: '12:30 PM',
    duration: '2 hrs',
    customerName: 'Emily Davis',
    customerInitials: 'ED',
    petName: 'Charlie',
    breed: 'French Bulldog',
    petEmoji: '🐩',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBv8qk7MPnhxfYrjdsJNgAENsxTXK0yuLukz8HeFWgDBKRmGA3FR8fEOdn0LnFDBJXb-nLWry2tRuQXxPdRh-tw-c6dXt85qvK5mwlNzSlwYS3BiDxh_-jmKLWpqbO20k4PsGItryuyxYyK--xRsWJk1fh1qD3YiJJ9Ncax6ZOK8dxstyDbFwE2hxuRmYc6nVHgO_MtTAvrNfQOmKxcDTtXF47kdFDV-itp9crICMSnYbxEbAXZxXUF',
    serviceName: 'Bath & Brush',
    staffName: 'Jessica L.',
    staffInitials: 'JL',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDainet1ubRrZKHn3GQzWL0843lj8m2X7XN8xfZb0gEMB4kmpZaw1j34s2GB3dp7VgM50H5j2KfiZxUOgFz5ZEkuoXvh63NHUUQbgc2yqCsH7Jl0ct12fjS1_IYxlzAwChQc_y_k-gTSyBzU4NWE2b8Zh4txFD2oa7bTYijzlo9oOBdfPakK5icwnAbCK0kjHsv6lx1jROpkHkAU8xvOu-LuwycToGWUdO2xTFWeFTNt9_VsDFDcT51',
    location: 'Main Location',
    status: 'Confirmed',
    price: 55.0,
    paymentStatus: 'Paid in Full',
    notes: 'Sanitary trim, ear cleaning.',
  },
  {
    id: 'appt-104',
    date: '2025-05-16',
    time: '2:30 PM',
    duration: '2.5 hrs',
    customerName: 'David Wilson',
    customerInitials: 'DW',
    petName: 'Max',
    breed: 'Labrador Retriever',
    petEmoji: '🐕‍🦺',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAFXa4L0Y26pDui6Qk6H8n5jTfmWem9SXA4SvHvkAQWmTy9LWBOVQENTZ3wIYZyreaoG9005ZHEUEsYKoLJGnlsKUOawaKEPqubNrLx3EF8lDmGpusSO9m0u14mh-tOJdslm1324XOadgfyLRY5VUPp0epefdBe5--NIEEDPOIWGp7ZtXYlSn6YcJPAiIpXdTjM3HyeMMROhg_ywmLhO9W8dqLS-zg5xdjmBeu5TS0mPL3r7tqkCbwv',
    serviceName: 'Full Groom',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAHTlKccB4ceDFdGfE6cit5A-0m6-mrlPsB3a-OPT-N04ZJCJWmRM4-1UDtvDpslTZNqQkXKb2JxrHjYkPDKiPV25CY-fhch3VC8-XZBaBgIx3XEHu-zosSUXCUWIhvZTicmxGtPPZS7OC8v7VkHB_T2ORMJB3imDu2s0Uqaz6e6yqi-mbahsZ1Z8ZFwoqwbjITX8sUd6SSvYNTOhLYRKu4667Dn4hw0WAE0jnW9q830nWYOLR4FhtY',
    location: 'Main Location',
    status: 'Checked In',
    price: 85.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 25.0,
    notes: 'Short summer cut, nail grinding.',
  },
  {
    id: 'appt-105',
    date: '2025-05-16',
    time: '4:30 PM',
    duration: '2.5 hrs',
    customerName: 'Jennifer Lee',
    customerInitials: 'JL',
    petName: 'Daisy',
    breed: 'Maltese',
    petEmoji: '🐾',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqSDv4fNbAxvgOx9NsYm8-bhQc-iI6slHTPsR9PJ8mzfK6FJJC4jGxMnTxFDMtFlw4K33NXb7AG4Ta5H5ZWforHhuQL0dDEYmlsYlWEBXsx5vJBCqo6UEArqQAr_IBV4rZH2Io6uPsBIC4Lb112btVY1Ng68xLf0UJjXygPwybHefDZx9LWPYv5jz02v59aRhQdL_gFidXrGw48N0jhrqY6mksNX1o8QsD6PBg-Q2yok72Fpibz-nR',
    serviceName: 'Deluxe Spa',
    staffName: 'Mike R.',
    staffInitials: 'MR',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7TGOeJQW7eT5f7skDkpc8TkqUWc0xKfX4q8qec9CgfCRtFUJDiSlys_NZ_R7zPBSl3nvm_Aka_5PTzw4rlPesEnrTuwcuwmrPM7soVYflmTwmc17RTihMw0evwfwdaFH6q2rJtCKXC-X5lZ7ShC8g1d4g7aaP5CuQ1aA21TQc5g36sMtCy9PV9ed0BHgJ4kgjKOgQb96E8C_C-Si1qSs4fE5XpHbCAq1IfoKKdJY-wkYeisX_zbZb',
    location: 'Main Location',
    status: 'In Progress',
    price: 95.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 30.0,
    notes: 'Blueberry facial and coat conditioning.',
  },
  {
    id: 'appt-106',
    date: '2025-05-16',
    time: '6:30 PM',
    duration: '1.5 hrs',
    customerName: 'Chris Brown',
    customerInitials: 'CB',
    petName: 'Rocky',
    breed: 'Boxer',
    petEmoji: '🐶',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUWuGGXiRighYziwqTjUyY6GkeuKLmIzlE1i-REMMf1JCsbBwmGpebbfsCHoqJV1LrsLsM6XIsrZxWIGi-fHJ7qA-r30gD6N6bnKHywJ-r0gNcT3hJpiZfQXBu5qo7DPSqGNeriMIjjt5ob-QUZmRQXz8fwkO2PqUWofWG2r9cffVLMY2uyQIlbw4NRDgwiv_PAXt4sh7cEujAipG1tLJdXu1DTvwyIWLnLpfHyuriMCITm-Vn8CWR',
    serviceName: 'Nail Trim',
    staffName: 'Jessica L.',
    staffInitials: 'JL',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBg5MBCkFd7lRq4N29PGSJFEPrR14j90mW2bLeiD_SjbiGT3qXnDx3klJWukTTn0Jce3Rz-H9DWMNc0uhbMycQx5ikIeoGzr_FSexaZZNKyh3m55zKlSYvjy03WrR1sZ0oFymjq0DKC4xGzHCS2nZhXjqt9YUw_zBv1IrpXlQx4qc1dQNrcYOt1Irv2blrhs3ErrkfIWypTKgdEnUk9z5rMd1Z86Zkuk9tcjqVIEyyTh0mqFOUCigOq',
    location: 'Main Location',
    status: 'Confirmed',
    price: 20.0,
    paymentStatus: 'Paid in Full',
    notes: 'Quick nail trim & paw balm.',
  },

  // Saturday, May 17, 2025 (Tomorrow)
  {
    id: 'appt-107',
    date: '2025-05-17',
    time: '8:00 AM',
    duration: '2.5 hrs',
    customerName: 'Amanda Garcia',
    customerInitials: 'AG',
    petName: 'Cooper',
    breed: 'Golden Retriever',
    petEmoji: '🐕',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUDcE0rJS9ds2jLo03T-0u3uSi0lQw5o1jz-No9f5om1qrjkbk-NxliY3nOxWQ4peWGmKZzG8SkUwmUdnKPSgvJkYfU7nkH9kUOZirQqDbpVorDY4hqnnDYH7-pGBXvLyzgcCNHYjj-LAHTju7YBP2rl3ysl58DNI1gDIJYzvasx3jDrP2b1tfKe5Y-Xwd3tRidj9DV5EA3WY-HNCZNy5sXrnw437TS1wxu9DSOeaxcz3EPWl1l848',
    serviceName: 'Full Groom',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD99ba3oDE0cSdvg6EMtIqmnht1AIZJkwq4CIRAbBPmXzio3OMaM1zMqMSGWqcnAuT_8lP5uP9l3fCxYqw4WSlxBIf2RtavVGc3F7fPGSiBYzYSpqPr_wCaqzvoP0FPHMAe57FRN6myqNIFRkuK_Hku7AAab0wu4gySYdVrInsLhN-EwPOe8mbivg2ZDWerDoaQUIQQZCsljXEujNZQb0B1H2znN-pIMIDXQETaTZIYWWIFb2KK61tD',
    location: 'Main Location',
    status: 'Scheduled',
    price: 85.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 25.0,
    notes: 'Breed standard scissor finish.',
  },
  {
    id: 'appt-108',
    date: '2025-05-17',
    time: '9:30 AM',
    duration: '2.5 hrs',
    customerName: 'Tom Anderson',
    customerInitials: 'TA',
    petName: 'Bailey',
    breed: 'Australian Shepherd',
    petEmoji: '🐶',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVU_3p2KwmZRGv-1xZ0Jjvo992UhKXSswMbDdvB7Dcae0Okuzkh2o7VcySF8sGUQFH3_TSgg9ZKgXgxRIuMKUsnvU_NbzgVuS6nFFiAeSXQezR85N9kVac6Y0PRRqs2kyHYoJoxJjdaza1ChRvjBlpF_uZyT3YgiAQ4uWO0eJ-JG7olZARSuNrCWIiB4nClJxAMEayZQtnYl68--8Mwe-YkzVuQJAmKCBJu5wyDLTrr3lfoIHdcMsl',
    serviceName: 'Full Groom + Add-ons',
    staffName: 'Mike R.',
    staffInitials: 'MR',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClrdhHdXOY7EJT7ugtQ6iSFqQUyzxZJSHz84z26PiQAGgM_E-sVhf9hk1aNCKSS2WPvUUaAbHxVqE31oVA4gQhq_tas-cZeYwUElnXwYZJc7oOku15NkKwfi5C6pkL7-HN-SMJ4HpwahSqJac_DACyzKTXUof2u1vgpu-Nn4v_GFigNo1mxpUlfaWz_QZRDSjgTXuSxPYhQfdGj-kBVF2ZOLyoGpjXJj9wj6RuoI3U1bvoyxBRyKxQ',
    location: 'Main Location',
    status: 'Scheduled',
    price: 110.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 40.0,
    notes: 'De-shedding package & sanitary trim.',
  },
  {
    id: 'appt-109',
    date: '2025-05-17',
    time: '11:00 AM',
    duration: '2 hrs',
    customerName: 'Lisa White',
    customerInitials: 'LW',
    petName: 'Zoe',
    breed: 'Yorkshire Terrier',
    petEmoji: '🐩',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCc_IEtzpwZifxx0x8UMPqs99WrL61SYVoz2G0-4kks6Fu3tbYdPDeTUr-AOehVVjI5BsA5EgqcySnLBVceK4qQW4OucAjQ0BxEAlHmr4o47ElvqdbikOpenAOfrGMX0ke_rbxlr7ojEHTRGRmXjjUcunKGAXSUBDnNFt0cJY3e5O_F8p5G0gtawF4GbMzUJaMdDXhdu8xlw6jRr5iR7namdCj6rY9kvih6ZyKmA3BnmQgusuyOIzPp',
    serviceName: 'Bath & Brush',
    staffName: 'Jessica L.',
    staffInitials: 'JL',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBpT9Ic9qUcVWaep5_Rul6W3rA769h0W1GJ9oD_KG65vBp8-v--_8lTMLuBhn7ekF_PNTYB6MSeGlHl4jmwnTEyVSGp00Eg4Nq3yLgHu9qlu3NYy1fMZs0Big9y8evtYMOOn5z72eaDzes7SvmEsWcd1355wFFxmwAFLHxL7rozYDjy12YsofGsOqlERs5-jBSLvI82YWqv1foQU1uOSPBvOuJxDbMqmw1IfW-bWZyQIbGrEVF2N3iF',
    location: 'Main Location',
    status: 'Waitlisted',
    price: 45.0,
    paymentStatus: '—',
    notes: 'Flexible with timing if cancellation arises.',
  },
  {
    id: 'appt-110',
    date: '2025-05-17',
    time: '1:00 PM',
    duration: '2.5 hrs',
    customerName: 'Brandon Taylor',
    customerInitials: 'BT',
    petName: 'Milo',
    breed: 'Beagle',
    petEmoji: '🐕',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCTEO3s6lMZ9_uJeSAlYsEVkJUarfJ85XlH8Ij5Byfm5kMpfWVdmZBHA30HNKKGMZpyDKLR15J8Jhu7YRn3yjS1x4kNKC9fVR86XTDhlv8MUhuIgnasDXnlE77ydtOHOMwUI8024UXWp6KtZ_-TUOtWsGawmK7AJU6xo7WlmqprGQOMizl_BP5iA48etzuvidHLDimJbP7i5cfy6PS_BmtbC4bUnamnRpDIlARHL6OwaKwlVAEcQz1E',
    serviceName: 'Deluxe Spa',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAPl8N-NCfG4_SXMwoNq7BY4dZrXxoGK44iSin4gBEYNDsO53gdhv_VzXY4BfMOOnepqMdcfHSGmepsPlBZgKYLZhQQX24DmEcEAm89ss-Ou0CYuOB5mTRxR6yBPPob4SXZs19oDNFxF3iJiFiI8eCdlqdockNfsgt4yks0guBwc4SOToNwrmu5X03Q3YUVDzhagJ1InlAWR2u8yIHFDMCQstZHzxRF5V_8CPOCshYi65lkJpIK3sVs',
    location: 'Main Location',
    status: 'Confirmed',
    price: 85.0,
    paymentStatus: 'Paid in Full',
    notes: 'Special lavender bath & ear cleaning.',
  },
  {
    id: 'appt-111',
    date: '2025-05-17',
    time: '3:30 PM',
    duration: '2.5 hrs',
    customerName: 'Rachel Green',
    customerInitials: 'RG',
    petName: 'Phoebe',
    breed: 'Bichon Frise',
    petEmoji: '🐩',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBxBpu7iqBtFvzvfeuISMdHu4ZV2zbPA0Z52jUHmE6QNgf3j1dTxa2mJLZyf9-XAQagthzK0xzjLV1BaTuyHcJ-8NRFenaG831v7BhQbb5cyvutTXqAGhE7vITkVku3dcJ_s1vweA2BW2ECbTIyjbv08XAHuL5KaQW_Mx3HfIlqkWldpiBGQM4QWKCPhs9QlGM9wTUqUY_RXjLbeFOhDSKpKhX8rBPwK59lnx2oei6VEH3KPdhan8jq',
    serviceName: 'Full Groom',
    staffName: 'Mike R.',
    staffInitials: 'MR',
    staffAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuATj2p_2BSf-YrNX1Rok8GfsAWUdgNRZ_GoQFrkRx79GbQIiDbnQPK7YGpSoQ4ADVqt8u_HuB2Lwof64NRScgQDhqeY9i5XB_20zeucwOvCHHFEfdHGl6tPyIPrg44ZJanNsz2Zn-DvvtcogX6yvt5ro249rq0EkrmbOdzcpiEf40vcgcA9UNALSQZ802ARoJUs5XasNqyx7brxAj1k1Sk8-Pjq5OrutxugzEB4TQBcYOLY54T2ktrO',
    location: 'Main Location',
    status: 'Scheduled',
    price: 85.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 25.0,
    notes: 'Fluffy round head cut.',
  },

  // Next Week Schedule (This Week / Next 7 Days)
  {
    id: 'appt-112',
    date: '2025-05-18',
    time: '10:00 AM',
    duration: '2 hrs',
    customerName: 'Olivia Benson',
    customerInitials: 'OB',
    petName: 'Koda',
    breed: 'Husky',
    petEmoji: '🐕‍🦺',
    serviceName: 'Bath & Brush',
    staffName: 'Jessica L.',
    staffInitials: 'JL',
    location: 'Main Location',
    status: 'Confirmed',
    price: 65.0,
    paymentStatus: 'Paid in Full',
    notes: 'High-velocity undercoat dry.',
  },
  {
    id: 'appt-113',
    date: '2025-05-19',
    time: '8:00 AM',
    duration: '1.5 hrs',
    customerName: 'Kevin Martinez',
    customerInitials: 'KM',
    petName: 'Teddy',
    breed: 'Shih Tzu',
    petEmoji: '🐶',
    serviceName: 'Nail Trim',
    staffName: 'Jessica L.',
    staffInitials: 'JL',
    location: 'Main Location',
    status: 'Scheduled',
    price: 20.0,
    paymentStatus: 'Paid in Full',
    notes: 'Quick nail grind and ear wipe.',
  },
  {
    id: 'appt-114',
    date: '2025-05-20',
    time: '10:00 AM',
    duration: '2.5 hrs',
    customerName: 'Daniel James',
    customerInitials: 'DJ',
    petName: 'Rex',
    breed: 'German Shepherd',
    petEmoji: '🐕',
    serviceName: 'Full Groom',
    staffName: 'Mike R.',
    staffInitials: 'MR',
    location: 'Main Location',
    status: 'Scheduled',
    price: 115.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 25.0,
    notes: 'De-shedding and desensitization.',
  },
  {
    id: 'appt-115',
    date: '2025-05-21',
    time: '1:00 PM',
    duration: '2.5 hrs',
    customerName: 'Sophia Patel',
    customerInitials: 'SP',
    petName: 'Loki',
    breed: 'Samoyed',
    petEmoji: '🐾',
    serviceName: 'Deluxe Spa',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    location: 'Main Location',
    status: 'Confirmed',
    price: 130.0,
    paymentStatus: 'Paid in Full',
    notes: 'Deep conditioning whitening shampoo.',
  },
  {
    id: 'appt-116',
    date: '2025-05-22',
    time: '9:00 AM',
    duration: '2 hrs',
    customerName: 'Matthew Brown',
    customerInitials: 'MB',
    petName: 'Bear',
    breed: 'Newfoundland',
    petEmoji: '🐕‍🦺',
    serviceName: 'Bath & Brush',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    location: 'Main Location',
    status: 'Scheduled',
    price: 90.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 20.0,
    notes: 'Gentle handling on rear hips.',
  },
  {
    id: 'appt-117',
    date: '2025-05-23',
    time: '3:30 PM',
    duration: '2.5 hrs',
    customerName: 'James Cooper',
    customerInitials: 'JC',
    petName: 'Buster',
    breed: 'Golden Retriever',
    petEmoji: '🐶',
    serviceName: 'Full Groom + Add-ons',
    staffName: 'Mike R.',
    staffInitials: 'MR',
    location: 'Main Location',
    status: 'Scheduled',
    price: 110.0,
    paymentStatus: 'Deposit Paid',
    depositAmount: 40.0,
    notes: 'Feather trim & teeth brushing.',
  },

  // Past Appointments
  {
    id: 'appt-past-1',
    date: '2025-05-15',
    time: '1:00 PM',
    duration: '2.5 hrs',
    customerName: 'Robert Johnson',
    customerInitials: 'RJ',
    petName: 'Duke',
    breed: 'Great Dane',
    petEmoji: '🐕',
    serviceName: 'Full Groom',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    location: 'Main Location',
    status: 'Completed',
    price: 85.0,
    paymentStatus: 'Paid in Full',
    notes: 'Full coat blowout and nail clip completed.',
  },
  {
    id: 'appt-past-2',
    date: '2025-05-15',
    time: '3:30 PM',
    duration: '2 hrs',
    customerName: 'Laura Wilson',
    customerInitials: 'LW',
    petName: 'Bella',
    breed: 'Cockapoo',
    petEmoji: '🐩',
    serviceName: 'Bath & Brush',
    staffName: 'Jessica L.',
    staffInitials: 'JL',
    location: 'Main Location',
    status: 'Completed',
    price: 55.0,
    paymentStatus: 'Paid in Full',
    notes: 'Tear stain removal treatment.',
  },
  {
    id: 'appt-past-3',
    date: '2025-05-14',
    time: '10:00 AM',
    duration: '2.5 hrs',
    customerName: 'Michael Smith',
    customerInitials: 'MS',
    petName: 'Rocco',
    breed: 'Pitbull',
    petEmoji: '🐕‍🦺',
    serviceName: 'Full Groom',
    staffName: 'Mike R.',
    staffInitials: 'MR',
    location: 'Main Location',
    status: 'Completed',
    price: 85.0,
    paymentStatus: 'Paid in Full',
    notes: 'Medicated oatmeal bath.',
  },
  {
    id: 'appt-past-4',
    date: '2025-05-14',
    time: '2:00 PM',
    duration: '2.5 hrs',
    customerName: 'Natalie Lee',
    customerInitials: 'NL',
    petName: 'Coco',
    breed: 'Pomeranian',
    petEmoji: '🐶',
    serviceName: 'Deluxe Spa',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    location: 'Main Location',
    status: 'Completed',
    price: 90.0,
    paymentStatus: 'Paid in Full',
    notes: 'Lion cut trim with fluffy tail.',
  },
  {
    id: 'appt-past-5',
    date: '2025-05-13',
    time: '11:30 AM',
    duration: '2.5 hrs',
    customerName: 'Jason Brown',
    customerInitials: 'JB',
    petName: 'Bentley',
    breed: 'Cavalier King Charles',
    petEmoji: '🐕',
    serviceName: 'Full Groom',
    staffName: 'Jessica L.',
    staffInitials: 'JL',
    location: 'Main Location',
    status: 'Completed',
    price: 75.0,
    paymentStatus: 'Paid in Full',
    notes: 'Ear trim and sanitary cut.',
  },

  // Canceled & No-Show Appointments
  {
    id: 'appt-canc-1',
    date: '2025-05-14',
    time: '9:00 AM',
    duration: '2.5 hrs',
    customerName: 'Patrick Adams',
    customerInitials: 'PA',
    petName: 'Buster',
    breed: 'Labrador',
    petEmoji: '🐶',
    serviceName: 'Full Groom',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    location: 'Main Location',
    status: 'Canceled',
    cancellationReason: 'Canceled by Customer',
    canceledAt: 'May 13, 2025 2:30 PM',
    notes: 'Severe thunderstorm in area.',
  },
  {
    id: 'appt-canc-2',
    date: '2025-05-14',
    time: '1:00 PM',
    duration: '2 hrs',
    customerName: 'Amanda Clark',
    customerInitials: 'AC',
    petName: 'Daisy',
    breed: 'Beagle',
    petEmoji: '🐕',
    serviceName: 'Bath & Brush',
    staffName: 'Jessica L.',
    staffInitials: 'JL',
    location: 'Main Location',
    status: 'Canceled',
    cancellationReason: 'Canceled by Salon',
    canceledAt: 'May 14, 2025 9:00 AM',
    notes: 'Groomer unavailable due to illness.',
  },
  {
    id: 'appt-canc-3',
    date: '2025-05-14',
    time: '3:30 PM',
    duration: '2.5 hrs',
    customerName: 'Brian Taylor',
    customerInitials: 'BT',
    petName: 'Stella',
    breed: 'Golden Retriever',
    petEmoji: '🐾',
    serviceName: 'Full Groom',
    staffName: 'Mike R.',
    staffInitials: 'MR',
    location: 'Main Location',
    status: 'Canceled',
    cancellationReason: 'Canceled by Customer',
    canceledAt: 'May 14, 2025 10:10 AM',
    notes: 'Work schedule conflict.',
  },
  {
    id: 'appt-canc-4',
    date: '2025-05-13',
    time: '10:00 AM',
    duration: '2.5 hrs',
    customerName: 'Nicole Harris',
    customerInitials: 'NH',
    petName: 'Daisy',
    breed: 'Maltese',
    petEmoji: '🐶',
    serviceName: 'Deluxe Spa',
    staffName: 'Sarah M.',
    staffInitials: 'SM',
    location: 'Main Location',
    status: 'Canceled',
    cancellationReason: 'Canceled by Customer',
    canceledAt: 'May 12, 2025 6:45 PM',
    notes: 'Family travel plans changed.',
  },
  {
    id: 'appt-canc-5',
    date: '2025-05-12',
    time: '1:00 PM',
    duration: '2.5 hrs',
    customerName: 'Eric Martin',
    customerInitials: 'EM',
    petName: 'Max',
    breed: 'Doodle',
    petEmoji: '🐕‍🦺',
    serviceName: 'Full Groom',
    staffName: 'Jessica L.',
    staffInitials: 'JL',
    location: 'Main Location',
    status: 'No Show',
    cancellationReason: 'No Show',
    canceledAt: 'May 12, 2025 1:15 PM',
    notes: 'Client did not arrive; non-refundable deposit retained.',
  },

  // Waitlist Appointments
  {
    id: 'appt-wait-1',
    customerName: 'Lisa White',
    customerInitials: 'LW',
    petName: 'Zoe',
    breed: 'Yorkshire Terrier',
    petEmoji: '🐩',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDwsX59GMopYLsPIzFFiDs4av3ZJZVxze9i4udG7019pXlkDslqVWgboVS47L64y81_2b89G7Wok9_jDdYDWmxBekeRUjYRp1DnrEOCgYzgIQG1WPO3yyTmcCn9RM4Gs1XoMtnAmkcRsHImvfB4OVtG69dgiRJWEwdxN_1BpdzBaiow5rFh9z9tNDLLBsAYahMxkjemdcC16Cxm_7z4gJxo3LxMpdJws_QdGIOQuVlk4M69-k5c2QO5',
    serviceName: 'Bath & Brush',
    preferredDate: 'Anytime',
    addedOn: 'May 16, 2025',
    notes: 'Morning preferred',
    status: 'Waitlisted',
    location: 'Main Location',
  },
  {
    id: 'appt-wait-2',
    customerName: 'Amanda Garcia',
    customerInitials: 'AG',
    petName: 'Cooper',
    breed: 'Golden Retriever',
    petEmoji: '🐕',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDH5B0zqQxmBJ-zlPwjDDXNwTLO_JyuMZ2nC0X3s0vVBFFTUGKtaJNbyy5vXZkF2oCDyfftbiG-n52gq5qCA2A5-dPw5gQta7XwQk_CHY831xl79at37oAoNyncjen9kD2eT0VhbM5RKUFNIdiziFe9NDPoYDcoFd0fLsfPLr_Y1u10mspYopi8KcBSx6qvriYxcVm5P7r4bDg3azQ7LXGOSSvNzEwhAHLHsOZ00N9TqK03elwfmdMc',
    serviceName: 'Full Groom',
    preferredDate: 'May 17, 2025',
    addedOn: 'May 15, 2025',
    notes: 'Before 10 AM',
    status: 'Waitlisted',
    location: 'Main Location',
  },
  {
    id: 'appt-wait-3',
    customerName: 'Kevin Martinez',
    customerInitials: 'KM',
    petName: 'Teddy',
    breed: 'Shih Tzu',
    petEmoji: '🐶',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBZcULBanZ9Lzo0wjue--R9yf8tRAEdat9CyP0C9LT-kX6AmktL0RgziadKz4qghgdlyY3pJChTgT4wfvdLa_veW_PWGJxeTYBMDzk_1YP7YRZse89TT_h-YSKP56tWYpiF_xiQWVTwu-mcUwuCed8tUghw2gmCNngZfTBzCC3gsxm0NW-z6ygAstjYBQs9fmLLIKUoU2u0bN7yXJixqTSju2I7LqnFHlnbC4osOZwsL-x_538yJ9Qo',
    serviceName: 'Nail Trim',
    preferredDate: 'May 19, 2025',
    addedOn: 'May 14, 2025',
    notes: 'Flexible',
    status: 'Waitlisted',
    location: 'Main Location',
  },
  {
    id: 'appt-wait-4',
    customerName: 'Emily Davis',
    customerInitials: 'ED',
    petName: 'Charlie',
    breed: 'French Bulldog',
    petEmoji: '🐾',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6g7eWFOEMjiDZV-_MdiwvHMtu8Opzwfc6MI6ibm5g9HhDWuxkqMzJm0qx8JQLiBowPvZQp3ZCNEANH7gRS9P5IkClBbeI39aefcMSMxo4lgXuYWvT4EUE_tB_81Zqw-0bxyuF-g_g4HHFpmR1skYr_70-8dbKcWoE2VkGU9MqDEdoHjnGNNp4VV456Or0JHwILSWpXrLXnaSI44uVYr-py9elOh745bBR_xqO7kWRwd0WrhkLe_Sb',
    serviceName: 'Full Groom',
    preferredDate: 'May 20, 2025',
    addedOn: 'May 14, 2025',
    notes: '—',
    status: 'Waitlisted',
    location: 'Main Location',
  },
  {
    id: 'appt-wait-5',
    customerName: 'Rachel Green',
    customerInitials: 'RG',
    petName: 'Phoebe',
    breed: 'Bichon Frise',
    petEmoji: '🐩',
    petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD9D3iXNQUluhZv9xQ0yQf2YdSzKdOJtGVWfvQzGZX_7AgEGFocdo0o1brSBIaIEeI8UMorpGxuZ8YQgcBMP2S02SaCyak8_TVzZnH3Qo8p1-G9mqo2Amkb9vUAHA_g_NeCxEzYd3Lc95RGm0i7UjGajKnglf8QmSOYdtQ-FFBLUJyZLDPehe6g91ZgSL6SGfsCat629aAoKbLIy_awUc1rKgc19qdSj7z08BaQv8lOQTaZedFpd0A6',
    serviceName: 'Full Groom',
    preferredDate: 'May 22, 2025',
    addedOn: 'May 13, 2025',
    notes: 'Can do late morning',
    status: 'Waitlisted',
    location: 'Main Location',
  },
];
