import { 
  KPIMetric, 
  AppointmentItem, 
  StaffScheduleItem, 
  FunnelStage, 
  GroomingRecord, 
  AlertNotification,
  Customer,
  PetRecord,
  ServiceItem,
  ProductItem,
  LocationItem,
  CustomerFullProfile,
  GroomerAppointmentItem
} from './types';

export const KPI_METRICS: KPIMetric[] = [
  {
    id: 'kpi-1',
    label: "Today's Appointments",
    value: "28",
    change: "12%",
    period: "vs yesterday",
    isPositive: true,
    iconName: 'calendar',
    colorTheme: 'purple',
  },
  {
    id: 'kpi-2',
    label: "Today's Revenue",
    value: "$6,842.50",
    change: "18%",
    period: "vs yesterday",
    isPositive: true,
    iconName: 'currency-dollar',
    colorTheme: 'emerald',
  },
  {
    id: 'kpi-3',
    label: "New Customers (30d)",
    value: "46",
    change: "15%",
    period: "vs last 30 days",
    isPositive: true,
    iconName: 'user-plus',
    colorTheme: 'blue',
  },
  {
    id: 'kpi-4',
    label: "No Show Rate (30d)",
    value: "4.2%",
    change: "1.3%",
    period: "vs last 30 days",
    isPositive: true, // down is good for no show rate
    iconName: 'paw-print',
    colorTheme: 'amber',
  },
  {
    id: 'kpi-5',
    label: "Rebook Rate (30d)",
    value: "68%",
    change: "6%",
    period: "vs last 30 days",
    isPositive: true,
    iconName: 'arrows-clockwise',
    colorTheme: 'rose',
  },
];

export const INITIAL_APPOINTMENTS: AppointmentItem[] = [
  {
    id: 'appt-1',
    time: '8:30 AM',
    petName: 'Buddy',
    breed: 'Golden Retriever',
    petEmoji: '🐶',
    serviceName: 'Full Groom',
    status: 'Checked In',
    price: 95.0,
    notes: 'Sensitive skin, hypoallergenic shampoo requested.',
  },
  {
    id: 'appt-2',
    time: '9:30 AM',
    petName: 'Luna',
    breed: 'Poodle',
    petEmoji: '🐩',
    serviceName: 'Full Groom + Add-ons',
    staffName: 'Mike R.',
    status: 'Scheduled',
    price: 120.0,
    notes: 'Puppy cut, trim teddy face shape, blueberry facial.',
  },
  {
    id: 'appt-3',
    time: '10:30 AM',
    petName: 'Max',
    breed: 'Doodle',
    petEmoji: '🐕',
    serviceName: 'Bath & Brush',
    staffName: 'Jessica L.',
    status: 'Scheduled',
    price: 65.0,
    notes: 'Brush out matting near ears, nail grind.',
  },
  {
    id: 'appt-4',
    time: '11:00 AM',
    petName: 'Bella',
    breed: 'Shih Tzu',
    petEmoji: '🐶',
    serviceName: 'Full Groom',
    staffName: 'Sarah M.',
    status: 'Scheduled',
    price: 85.0,
    notes: 'Short summer cut, leave tail fluffy.',
  },
  {
    id: 'appt-5',
    time: '1:00 PM',
    petName: 'Charlie',
    breed: 'French Bulldog',
    petEmoji: '🐾',
    serviceName: 'Nail Trim',
    staffName: 'Mike R.',
    status: 'Scheduled',
    price: 25.0,
    notes: 'Nail dremel and paw pad balm.',
  },
  {
    id: 'appt-6',
    time: '2:15 PM',
    petName: 'Daisy',
    breed: 'Maltese',
    petEmoji: '🐕',
    serviceName: 'Full Groom',
    staffName: 'Sarah M.',
    status: 'Scheduled',
    price: 85.0,
    notes: 'Sanitary trim, ear cleaning.',
  },
  {
    id: 'appt-7',
    time: '3:30 PM',
    petName: 'Rocky',
    breed: 'German Shepherd',
    petEmoji: '🐕‍🦺',
    serviceName: 'De-shedding Bath & Blowout',
    staffName: 'Taylor P.',
    status: 'Scheduled',
    price: 110.0,
    notes: 'Undercoat blowout, teeth brushing.',
  },
];

export const STAFF_SCHEDULES: StaffScheduleItem[] = [
  {
    id: 'staff-1',
    name: 'Sarah M.',
    role: 'Groomer',
    initials: 'SM',
    slots: ['booked', 'booked', 'booked', 'booked', 'booked', 'booked', 'booked', 'available', 'available'],
    appointmentsCount: 7,
    phone: '(555) 234-8901',
    commissionRate: 50,
  },
  {
    id: 'staff-2',
    name: 'Mike R.',
    role: 'Groomer',
    initials: 'MR',
    slots: ['booked', 'booked', 'booked', 'booked', 'booked', 'booked', 'break', 'available', 'available'],
    appointmentsCount: 6,
    phone: '(555) 345-6712',
    commissionRate: 50,
  },
  {
    id: 'staff-3',
    name: 'Jessica L.',
    role: 'Groomer',
    initials: 'JL',
    slots: ['booked', 'booked', 'booked', 'booked', 'booked', 'booked', 'break', 'available', 'available'],
    appointmentsCount: 6,
    phone: '(555) 456-7823',
    commissionRate: 50,
  },
  {
    id: 'staff-4',
    name: 'Taylor P.',
    role: 'Bather',
    initials: 'TP',
    slots: ['booked', 'booked', 'booked', 'booked', 'break', 'available', 'available', 'available', 'available'],
    appointmentsCount: 5,
    phone: '(555) 567-8934',
    commissionRate: 35,
  },
  {
    id: 'staff-5',
    name: 'Alex D.',
    role: 'Bather',
    initials: 'AD',
    slots: ['booked', 'booked', 'booked', 'break', 'available', 'available', 'available', 'available', 'available'],
    appointmentsCount: 4,
    phone: '(555) 678-9045',
    commissionRate: 35,
  },
];

export const BOOKING_FUNNEL: FunnelStage[] = [
  {
    stage: 'Website Visits',
    count: 412,
    subtext: 'Visits',
    conversionPercent: '45.9%',
    bgClass: 'bg-indigo-300',
    textClass: 'text-indigo-950',
  },
  {
    stage: 'Account Created',
    count: 189,
    subtext: 'Accounts',
    conversionPercent: '75.1%',
    bgClass: 'bg-indigo-400',
    textClass: 'text-white',
  },
  {
    stage: 'Intake Completed',
    count: 142,
    subtext: 'Intakes',
    conversionPercent: '83.1%',
    bgClass: 'bg-emerald-400',
    textClass: 'text-white',
  },
  {
    stage: 'Booked',
    count: 118,
    subtext: 'Appointments',
    conversionPercent: '81.4%',
    bgClass: 'bg-amber-300',
    textClass: 'text-amber-950',
  },
  {
    stage: 'Completed',
    count: 96,
    subtext: 'Grooms Finished',
    conversionPercent: undefined,
    bgClass: 'bg-rose-400',
    textClass: 'text-white',
  },
];

export const GROOMING_RECORDS: GroomingRecord[] = [
  {
    id: 'rec-1',
    petName: 'Buddy',
    breed: 'Golden Retriever',
    petEmoji: '🐶',
    date: 'May 12, 2025',
    serviceName: 'Full Groom',
    groomer: 'Sarah M.',
    amount: 95.0,
    status: 'Paid',
    cutDetails: 'Tidy outline, scissor paws, sanitary trim.',
    coatCondition: 'Healthy, slight undercoat build-up around flanks.',
  },
  {
    id: 'rec-2',
    petName: 'Luna',
    breed: 'Poodle',
    petEmoji: '🐩',
    date: 'May 11, 2025',
    serviceName: 'Full Groom + Add-ons',
    groomer: 'Mike R.',
    amount: 120.0,
    status: 'Paid',
    cutDetails: '#4 body, fluffy Asian-fusion ears, round teddy head.',
    coatCondition: 'Silky, clean ears, brushed thoroughly.',
  },
  {
    id: 'rec-3',
    petName: 'Charlie',
    breed: 'French Bulldog',
    petEmoji: '🐾',
    date: 'May 10, 2025',
    serviceName: 'Bath & Brush',
    groomer: 'Jessica L.',
    amount: 65.0,
    status: 'Paid',
    cutDetails: 'Deshed bath, ear flush, wrinkle balm treatment.',
    coatCondition: 'Short coat, wrinkle folds treated with chlorhexidine wipes.',
  },
  {
    id: 'rec-4',
    petName: 'Daisy',
    breed: 'Maltese',
    petEmoji: '🐕',
    date: 'May 9, 2025',
    serviceName: 'Full Groom',
    groomer: 'Sarah M.',
    amount: 85.0,
    status: 'Paid',
    cutDetails: 'Puppy trim, sanitary clip, round muzzle.',
    coatCondition: 'Clean, tear stains lightened with enzyme cleanser.',
  },
  {
    id: 'rec-5',
    petName: 'Ollie',
    breed: 'Cockapoo',
    petEmoji: '🐶',
    date: 'May 8, 2025',
    serviceName: 'Full Groom',
    groomer: 'Mike R.',
    amount: 105.0,
    status: 'Paid',
    cutDetails: '5/8" comb attachment on torso, hand scissored legs.',
    coatCondition: 'Excellent curly coat condition.',
  },
];

export const ALERTS_LIST: AlertNotification[] = [
  {
    id: 'alert-1',
    title: 'Vaccinations Expiring Soon',
    description: '12 pets have vaccinations expiring in 30 days',
    count: 12,
    type: 'vaccination',
    iconName: 'first-aid',
    bgIconColor: 'bg-rose-50 text-rose-600',
    badgeBg: 'bg-rose-100',
    badgeText: 'text-rose-700',
  },
  {
    id: 'alert-2',
    title: 'Unsigned Documents',
    description: '8 documents need customer signature',
    count: 8,
    type: 'document',
    iconName: 'file-text',
    bgIconColor: 'bg-amber-50 text-amber-600',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-700',
  },
  {
    id: 'alert-3',
    title: 'Upcoming Birthdays',
    description: '5 pets have birthdays this week',
    count: 5,
    type: 'birthday',
    iconName: 'cake',
    bgIconColor: 'bg-blue-50 text-blue-600',
    badgeBg: 'bg-blue-100',
    badgeText: 'text-blue-700',
  },
  {
    id: 'alert-4',
    title: 'Low Inventory',
    description: '7 products are running low',
    count: 7,
    type: 'inventory',
    iconName: 'package',
    bgIconColor: 'bg-purple-50 text-purple-600',
    badgeBg: 'bg-purple-100',
    badgeText: 'text-purple-700',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Emily Watson',
    email: 'emily.w@example.com',
    phone: '(555) 123-4567',
    pets: ['Buddy (Golden Retriever)'],
    totalSpent: 1140.0,
    lastVisit: 'May 12, 2025',
    preferredGroomer: 'Sarah M.',
  },
  {
    id: 'cust-2',
    name: 'David Miller',
    email: 'david.m@example.com',
    phone: '(555) 234-5678',
    pets: ['Luna (Poodle)'],
    totalSpent: 1440.0,
    lastVisit: 'May 11, 2025',
    preferredGroomer: 'Mike R.',
  },
  {
    id: 'cust-3',
    name: 'Rachel Green',
    email: 'rachel.g@example.com',
    phone: '(555) 345-6789',
    pets: ['Max (Doodle)', 'Cooper (Beagle)'],
    totalSpent: 980.0,
    lastVisit: 'May 12, 2025',
    preferredGroomer: 'Jessica L.',
  },
  {
    id: 'cust-4',
    name: 'Marcus Vance',
    email: 'marcus.v@example.com',
    phone: '(555) 456-7890',
    pets: ['Charlie (French Bulldog)'],
    totalSpent: 620.0,
    lastVisit: 'May 10, 2025',
    preferredGroomer: 'Mike R.',
  },
  {
    id: 'cust-5',
    name: 'Sophia Chen',
    email: 'sophia.c@example.com',
    phone: '(555) 567-8901',
    pets: ['Bella (Shih Tzu)', 'Daisy (Maltese)'],
    totalSpent: 2150.0,
    lastVisit: 'May 09, 2025',
    preferredGroomer: 'Sarah M.',
  },
];

export const INITIAL_PETS: PetRecord[] = [
  {
    id: 'pet-1',
    name: 'Buddy',
    breed: 'Golden Retriever',
    age: '4 yrs',
    weight: '68 lbs',
    ownerName: 'Emily Watson',
    emoji: '🐶',
    vaccinationStatus: 'Up to date',
    specialNotes: 'Loves head scratches, needs tear-less oatmeal shampoo.',
    lastGroomDate: 'May 12, 2025',
  },
  {
    id: 'pet-2',
    name: 'Luna',
    breed: 'Poodle',
    age: '2 yrs',
    weight: '45 lbs',
    ownerName: 'David Miller',
    emoji: '🐩',
    vaccinationStatus: 'Up to date',
    specialNotes: 'Asian fusion style head trim, blueberry facial.',
    lastGroomDate: 'May 11, 2025',
  },
  {
    id: 'pet-3',
    name: 'Max',
    breed: 'Goldendoodle',
    age: '3 yrs',
    weight: '52 lbs',
    ownerName: 'Rachel Green',
    emoji: '🐕',
    vaccinationStatus: 'Expiring Soon',
    specialNotes: 'Prone to ear tangles, brush thoroughly before bath.',
    lastGroomDate: 'May 12, 2025',
  },
  {
    id: 'pet-4',
    name: 'Charlie',
    breed: 'French Bulldog',
    age: '5 yrs',
    weight: '28 lbs',
    ownerName: 'Marcus Vance',
    emoji: '🐾',
    vaccinationStatus: 'Up to date',
    specialNotes: 'Wrinkle wipe treatment, sensitive paws.',
    lastGroomDate: 'May 10, 2025',
  },
  {
    id: 'pet-5',
    name: 'Bella',
    breed: 'Shih Tzu',
    age: '6 yrs',
    weight: '14 lbs',
    ownerName: 'Sophia Chen',
    emoji: '🐶',
    vaccinationStatus: 'Up to date',
    specialNotes: 'Gentle on back legs, loves strawberry spritz.',
    lastGroomDate: 'May 11, 2025',
  },
];

export const SERVICES_CATALOG: ServiceItem[] = [
  {
    id: 'srv-1',
    name: 'Full Groom - Large Breed (50+ lbs)',
    category: 'Full Groom',
    price: 95.0,
    durationMinutes: 90,
    description: 'Includes luxury bath, blow-dry, brush-out, full body haircut, nail trim, ear cleaning, and sanitary clip.',
  },
  {
    id: 'srv-2',
    name: 'Full Groom - Medium Breed (25-49 lbs)',
    category: 'Full Groom',
    price: 85.0,
    durationMinutes: 75,
    description: 'Complete styling, haircut, bath, blow dry, ear care, and paw pad trim.',
  },
  {
    id: 'srv-3',
    name: 'Full Groom - Small Breed (<25 lbs)',
    category: 'Full Groom',
    price: 75.0,
    durationMinutes: 60,
    description: 'Precision styling, hypoallergenic shampoo, sanitary cut, nail clip, ear cleaning.',
  },
  {
    id: 'srv-4',
    name: 'Bath & Brush Deluxe',
    category: 'Bath & Brush',
    price: 65.0,
    durationMinutes: 45,
    description: 'Double deep-clean shampoo, conditioner, 15-minute de-shed brush out, nail trim, ear flush.',
  },
  {
    id: 'srv-5',
    name: 'Blueberry Facial & Teeth Brushing Add-on',
    category: 'Add-on',
    price: 20.0,
    durationMinutes: 15,
    description: 'Tear-stain lightening blueberry scrub with enzymatic dental polish and fresh breath spray.',
  },
  {
    id: 'srv-6',
    name: 'Nail Trim & Dremel Filing',
    category: 'A La Carte',
    price: 25.0,
    durationMinutes: 15,
    description: 'Precision nail clipping and smooth round edge filing with soothing paw balm.',
  },
];

export const INVENTORY_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-1',
    name: 'Ultra-Hydrating Oatmeal Shampoo (1 Gallon)',
    sku: 'SHAMP-OAT-01',
    category: 'Shampoo',
    stock: 4,
    minStock: 8,
    price: 48.0,
  },
  {
    id: 'prod-2',
    name: 'Blueberry Tearless Facial Scrub (32 oz)',
    sku: 'FACE-BLUE-02',
    category: 'Treatment',
    stock: 2,
    minStock: 6,
    price: 32.0,
  },
  {
    id: 'prod-3',
    name: 'Silk Coat Detangling Spray (16 oz)',
    sku: 'COND-SILK-03',
    category: 'Treatment',
    stock: 5,
    minStock: 10,
    price: 24.0,
  },
  {
    id: 'prod-4',
    name: 'Gourmet Organic Beef Liver Bites (8 oz)',
    sku: 'TREAT-BEEF-04',
    category: 'Treats',
    stock: 18,
    minStock: 12,
    price: 14.5,
  },
  {
    id: 'prod-5',
    name: 'Seasonal Plaid Grooming Bandanas (50 pack)',
    sku: 'ACC-BAND-05',
    category: 'Accessories',
    stock: 3,
    minStock: 10,
    price: 35.0,
  },
  {
    id: 'prod-6',
    name: 'Japanese Steel 7.5" Curved Shears',
    sku: 'TOOL-SHEAR-06',
    category: 'Tools',
    stock: 2,
    minStock: 4,
    price: 180.0,
  },
];

export const INITIAL_LOCATIONS: LocationItem[] = [
  {
    id: 'loc-1',
    name: 'All About Pawz – Main Location',
    type: 'Main Location',
    address: '1234 Maple Drive, Suite 100',
    cityStateZip: 'Frisco, TX 75034',
    phone: '(214) 555-0100',
    email: 'main@allaboutpawz.com',
    manager: 'Sarah Jenkins',
    status: 'Active',
    stationCount: 8,
    operatingHours: 'Mon-Sat: 7:30 AM – 6:30 PM, Sun: Closed',
    isDefault: true,
  },
  {
    id: 'loc-2',
    name: 'All About Pawz – Westside Spa',
    type: 'Luxury Spa',
    address: '8820 Preston Rd, Building B',
    cityStateZip: 'Plano, TX 75024',
    phone: '(214) 555-0200',
    email: 'westside@allaboutpawz.com',
    manager: 'Mike Reynolds',
    status: 'Active',
    stationCount: 6,
    operatingHours: 'Tue-Sun: 8:00 AM – 7:00 PM, Mon: Closed',
    isDefault: false,
  },
  {
    id: 'loc-3',
    name: 'All About Pawz – Mobile Van #1',
    type: 'Mobile Van',
    address: 'Mobile Unit (North Metro Area)',
    cityStateZip: 'Dallas-Fort Worth, TX',
    phone: '(214) 555-0301',
    email: 'mobile1@allaboutpawz.com',
    manager: 'Alex Rivera',
    status: 'Active',
    stationCount: 2,
    operatingHours: 'Mon-Fri: 8:00 AM – 5:00 PM',
    isDefault: false,
  },
];

export const SARAH_JOHNSON_PROFILE: CustomerFullProfile = {
  id: 'cust-sarah-johnson',
  name: 'Sarah Johnson',
  status: 'Active Customer',
  phone: '(214) 555-0198',
  email: 'sarah.johnson@email.com',
  address: '1234 Maple Drive, Frisco, TX 75034',
  lifetimeValue: 1245.50,
  totalSpent: 1095.50,
  outstandingBalance: 0.00,
  loyaltyPoints: 245,
  customerSince: 'Apr 12, 2023',
  defaultPaymentMethod: {
    cardBrand: 'VISA',
    last4: '4242',
    expires: '04/27',
  },
  pets: [
    {
      id: 'pet-buddy-1',
      name: 'Buddy',
      breed: 'Golden Retriever',
      gender: 'Male',
      age: '4 yrs',
      birthDate: 'Mar 14, 2020',
      weight: '72 lbs',
      imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80',
      isPrimary: true,
      vaccinationsStatus: 'Up to date',
      medicalAlert: 'No Known Allergies',
      lastGroomDate: 'Apr 16, 2025',
      nextApptDate: 'May 16, 2025',
      nextApptType: 'Full Groom',
    },
    {
      id: 'pet-luna-2',
      name: 'Luna',
      breed: 'Poodle',
      gender: 'Female',
      age: '2 yrs',
      birthDate: 'Oct 2, 2021',
      weight: '18 lbs',
      imageUrl: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=400&q=80',
      isPrimary: false,
      vaccinationsStatus: 'Up to date',
      medicalAlert: 'Sensitive Skin',
      lastGroomDate: 'Apr 20, 2025',
      nextApptDate: 'May 20, 2025',
      nextApptType: 'Full Groom + Add-ons',
    },
  ],
  upcomingAppointments: [
    {
      id: 'appt-sj-1',
      month: 'MAY',
      day: '16',
      petName: 'Buddy',
      serviceName: 'Full Groom',
      time: '8:30 AM',
      duration: '2.5 hrs',
      groomer: 'Sarah M.',
      status: 'Scheduled',
      petImage: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=200&q=80',
    },
    {
      id: 'appt-sj-2',
      month: 'MAY',
      day: '20',
      petName: 'Luna',
      serviceName: 'Full Groom + Add-ons',
      time: '10:30 AM',
      duration: '2.5 hrs',
      groomer: 'Mike R.',
      status: 'Scheduled',
      petImage: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=200&q=80',
    },
    {
      id: 'appt-sj-3',
      month: 'JUN',
      day: '13',
      petName: 'Buddy',
      serviceName: 'Bath & Brush',
      time: '9:00 AM',
      duration: '1.5 hrs',
      groomer: 'Jessica L.',
      status: 'Scheduled',
      petImage: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=200&q=80',
    },
  ],
  paymentHistory: [
    {
      id: 'pay-sj-1',
      date: 'May 2, 2025',
      type: 'Payment',
      description: 'Full Groom – Buddy',
      amount: 95.00,
      status: 'Paid',
      method: 'Visa •••• 4242',
    },
    {
      id: 'pay-sj-2',
      date: 'Apr 18, 2025',
      type: 'Payment',
      description: 'Deposit – Buddy (May 16)',
      amount: 25.00,
      status: 'Paid',
      method: 'Visa •••• 4242',
    },
    {
      id: 'pay-sj-3',
      date: 'Apr 2, 2025',
      type: 'Payment',
      description: 'Full Groom – Luna + Add-ons',
      amount: 125.00,
      status: 'Paid',
      method: 'Visa •••• 4242',
    },
    {
      id: 'pay-sj-4',
      date: 'Mar 21, 2025',
      type: 'Invoice',
      description: 'Product Purchase (Shampoo)',
      amount: 24.50,
      status: 'Paid',
      method: 'Visa •••• 4242',
    },
    {
      id: 'pay-sj-5',
      date: 'Mar 10, 2025',
      type: 'Payment',
      description: 'Full Groom – Buddy',
      amount: 85.00,
      status: 'Paid',
      method: 'Visa •••• 4242',
    },
  ],
  recentActivity: [
    {
      id: 'act-sj-1',
      date: 'May 9, 2025',
      time: '10:30 AM',
      actor: 'System',
      actorType: 'System',
      description: 'Appointment Confirmed for Buddy on May 16, 2025',
    },
    {
      id: 'act-sj-2',
      date: 'May 2, 2025',
      time: '2:15 PM',
      actor: 'Sarah M.',
      actorType: 'Staff',
      description: 'Checked out – Buddy (Full Groom)',
    },
    {
      id: 'act-sj-3',
      date: 'Apr 18, 2025',
      time: '9:05 AM',
      actor: 'System',
      actorType: 'System',
      description: 'Deposit Paid – Buddy (May 16, 2025)',
    },
    {
      id: 'act-sj-4',
      date: 'Apr 10, 2025',
      time: '11:20 AM',
      actor: 'Sarah M.',
      actorType: 'Staff',
      description: 'Intake Form Updated for Luna',
    },
  ],
  communication: {
    lastEmailDate: 'May 9, 2025',
    lastEmailSubject: 'Appointment Reminder',
    lastSmsDate: 'May 9, 2025',
    lastSmsContent: 'Appointment Confirmed',
  },
};

export const DEMO_AUTH_USERS = [
  {
    email: 'admin@test.com',
    password: 'password',
    role: 'admin',
    name: 'Admin User',
    title: 'Salon Administrator',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    station: 'Central Management',
    description: 'Full access to financial analytics, staffing, settings, global POS, and all salon operations.',
  },
  {
    email: 'groomer@test.com',
    password: 'password',
    role: 'groomer',
    name: 'Sarah M.',
    title: 'Senior Pet Stylist & Lead Groomer',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    station: 'Station #3 (Spa Suite)',
    description: 'Direct station view, time-clocking, pet intake notes, live grooming lifecycle, and tips tracking.',
  }
];

export const INITIAL_GROOMER_APPOINTMENTS: GroomerAppointmentItem[] = [
  {
    id: 'g-appt-1',
    time: '8:30 AM',
    duration: '2h',
    petName: 'Buddy',
    breed: 'Golden Retriever',
    petImage: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=300&auto=format&fit=crop&q=80',
    serviceType: 'Full Groom',
    ownerName: 'Sarah M.',
    ownerPhone: '(214) 555-0198',
    ownerEmail: 'sarah.m@email.com',
    status: 'In Service',
    age: '4 years old',
    weight: '72 lbs',
    allergies: 'None',
    temperament: 'Friendly',
    lastGroomDate: 'Apr 14, 2025',
    price: 85.00,
    addons: [
      { name: 'Blueberry Facial', price: 15.00 }
    ],
    ownerNotes: 'Please keep the top a little longer. He gets nervous with nail trims so take your time. Thank you! 💙',
    internalNotes: [
      'Loves peanut butter treats',
      'Nervous with nail trims – go slow',
      'Prefers warm water',
      'Last incident: None'
    ],
    startTime: '9:32 AM',
  },
  {
    id: 'g-appt-2',
    time: '9:30 AM',
    duration: '1.5h',
    petName: 'Luna',
    breed: 'Poodle',
    petImage: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format&fit=crop&q=80',
    serviceType: 'Full Groom + Add-ons',
    ownerName: 'Mike R.',
    ownerPhone: '(214) 555-8842',
    ownerEmail: 'mike.r@email.com',
    status: 'In Service',
    age: '3 years old',
    weight: '18 lbs',
    allergies: 'Sensitive Skin (Oatmeal Shampoo)',
    temperament: 'Calm',
    lastGroomDate: 'May 1, 2025',
    price: 95.00,
    addons: [
      { name: 'Teeth Brushing', price: 12.00 },
      { name: 'De-mat Spray', price: 10.00 }
    ],
    ownerNotes: 'A little matted behind ears. Please trim teddy bear style.',
    internalNotes: [
      'Very sweet girl',
      'Tolerates blow dryer on low setting',
      'Owner tipped $20 last visit'
    ],
    startTime: '10:05 AM',
  },
  {
    id: 'g-appt-3',
    time: '11:00 AM',
    duration: '1.5h',
    petName: 'Max',
    breed: 'Goldendoodle',
    petImage: 'https://images.unsplash.com/photo-1591768575198-88dac53fbd0a?w=300&auto=format&fit=crop&q=80',
    serviceType: 'Bath & Brush',
    ownerName: 'Jessica L.',
    ownerPhone: '(214) 555-4921',
    ownerEmail: 'jess.l@example.com',
    status: 'In Service',
    age: '2 years old',
    weight: '45 lbs',
    allergies: 'None',
    temperament: 'Playful / High Energy',
    lastGroomDate: 'Mar 28, 2025',
    price: 65.00,
    addons: [
      { name: 'Nail Grind', price: 15.00 }
    ],
    ownerNotes: 'Please give him a fresh bath and brush out any burs from park.',
    internalNotes: [
      'High energy during drying',
      'Loves head scratches'
    ],
    startTime: '11:05 AM',
  },
  {
    id: 'g-appt-4',
    time: '12:30 PM',
    duration: '1h',
    petName: 'Charlie',
    breed: 'French Bulldog',
    petImage: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=300&auto=format&fit=crop&q=80',
    serviceType: 'Nail Trim & Wrinkle Clean',
    ownerName: 'Mike R.',
    ownerPhone: '(214) 555-8842',
    ownerEmail: 'mike.r@email.com',
    status: 'Scheduled',
    age: '5 years old',
    weight: '26 lbs',
    allergies: 'Chicken allergy',
    temperament: 'Stubborn / Sweet',
    lastGroomDate: 'Apr 22, 2025',
    price: 35.00,
    addons: [
      { name: 'Nose & Paw Balm', price: 8.00 }
    ],
    ownerNotes: 'Clean facial wrinkles thoroughly please.',
    internalNotes: [
      'Quick procedure, 20 mins max'
    ],
  },
  {
    id: 'g-appt-5',
    time: '1:30 PM',
    duration: '1.5h',
    petName: 'Bella',
    breed: 'Shih Tzu',
    petImage: 'https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=300&auto=format&fit=crop&q=80',
    serviceType: 'Full Groom',
    ownerName: 'Sarah M.',
    ownerPhone: '(214) 555-0198',
    ownerEmail: 'sarah.m@email.com',
    status: 'Ready for Pickup',
    age: '6 years old',
    weight: '14 lbs',
    allergies: 'None',
    temperament: 'Gentle',
    lastGroomDate: 'Apr 2, 2025',
    price: 75.00,
    addons: [
      { name: 'Bow & Bandana', price: 5.00 }
    ],
    ownerNotes: 'Summer puppy cut with cute ear bows.',
    internalNotes: [
      'Grooming completed at 1:15 PM',
      'Client notified by SMS'
    ],
  },
  {
    id: 'g-appt-6',
    time: '3:00 PM',
    duration: '1.5h',
    petName: 'Daisy',
    breed: 'Maltese',
    petImage: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=300&auto=format&fit=crop&q=80',
    serviceType: 'Full Groom + Add-ons',
    ownerName: 'Sarah M.',
    ownerPhone: '(214) 555-0198',
    ownerEmail: 'sarah.m@email.com',
    status: 'Scheduled',
    age: '3 years old',
    weight: '9 lbs',
    allergies: 'None',
    temperament: 'Shy',
    lastGroomDate: 'Mar 15, 2025',
    price: 80.00,
    addons: [
      { name: 'De-shedding Treatment', price: 20.00 }
    ],
    ownerNotes: 'Keep coat soft and fluffy.',
    internalNotes: [
      'Prefers female groomer'
    ],
  },
  {
    id: 'g-appt-7',
    time: '4:30 PM',
    duration: '1h',
    petName: 'Cooper',
    breed: 'Corgi',
    petImage: 'https://images.unsplash.com/photo-1612536057832-2ff7ead58194?w=300&auto=format&fit=crop&q=80',
    serviceType: 'Bath & Brush',
    ownerName: 'Alex D.',
    ownerPhone: '(214) 555-9302',
    ownerEmail: 'alex.d@example.com',
    status: 'Scheduled',
    age: '1.5 years old',
    weight: '28 lbs',
    allergies: 'None',
    temperament: 'Bouncy / Friendly',
    lastGroomDate: 'Apr 29, 2025',
    price: 55.00,
    addons: [
      { name: 'Undercoat Blowout', price: 15.00 }
    ],
    ownerNotes: 'Lots of shedding this spring!',
    internalNotes: [
      'Ready for blowout station'
    ],
  }
];


